# Generated by Django 4.0.3 on 2022-03-21 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('task', models.TextField()),
                ('progress_choice', models.CharField(blank=True, choices=[('Need_to_do', 'Need To Do'), ('In_progress', 'In Progress'), ('Finish', 'Finish')], default='Need_to_do', max_length=15)),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата обновления')),
            ],
        ),
    ]
