# Generated by Django 4.0.3 on 2022-03-14 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_task_progress_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_choice', models.CharField(blank=True, choices=[('Need_to_do', 'Need To Do'), ('In_progress', 'In Progress'), ('Finish', 'Finish')], max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='task',
            name='progress_choice',
        ),
    ]
